name: Dr. Phillip Snell
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6254363886546344
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.6056196223944426
  rhythmicContrast: 0.32699958933517337
purpose: []
